$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: time-series-forecasting
compute: azureml:cpu-cluster

jobs:

  region_job:
    environment:
      conda_file: auto_arima_conda.yml
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04@latest
    code: ./
    command: >-
      python auto_arima.py
      --train_folder ${{inputs.train_folder}}
      --train_file ${{inputs.train_file}}
      --eval_folder ${{outputs.eval_folder}}
      --ts_level_1 "${{inputs.ts_level_1}}"
      --ts_level_2 "${{inputs.ts_level_2}}"
      --ts_target "${{inputs.ts_target}}"
      --ts_test_horizon ${{inputs.ts_test_horizon}}
      --ts_forecast_horizon ${{inputs.ts_forecast_horizon}}
    inputs:
      train_folder:
        type: uri_folder
        path: azureml://datastores/datalake/paths/ts_train
      train_file: "train_region.csv"
      ts_level_1: "Region"
      ts_level_2: "Part Number"
      ts_target: "Units sold per Part"
      ts_test_horizon: 12
      ts_forecast_horizon: 12
    outputs:
      eval_folder:
        type: uri_folder
        path: azureml://datastores/datalake/paths/ts_eval

  state_job:
    environment:
      conda_file: auto_arima_conda.yml
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04@latest
    code: ./
    command: >-
      python auto_arima.py
      --train_folder ${{inputs.train_folder}}
      --train_file ${{inputs.train_file}}
      --eval_folder ${{outputs.eval_folder}}
      --ts_level_1 "${{inputs.ts_level_1}}"
      --ts_level_2 "${{inputs.ts_level_2}}"
      --ts_target "${{inputs.ts_target}}"
      --ts_test_horizon ${{inputs.ts_test_horizon}}
      --ts_forecast_horizon ${{inputs.ts_forecast_horizon}}
    inputs:
      train_folder:
        type: uri_folder
        path: azureml://datastores/datalake/paths/ts_train
      train_file: "train_state.csv"
      ts_level_1: "State"
      ts_level_2: "Part Number"
      ts_target: "Units sold per Part"
      ts_test_horizon: 12
      ts_forecast_horizon: 12
    outputs:
      eval_folder:
        type: uri_folder
        path: azureml://datastores/datalake/paths/ts_eval